# Generated by Django 5.1.4 on 2025-01-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_productcategory_alter_products_productcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="productcategory",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
    ]
