# Generated by Django 5.1.4 on 2025-01-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_productcategory_alter_products_productcategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="productname",
            new_name="name",
        ),
    ]
