# Generated by Django 5.1.4 on 2025-01-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_productname_products_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="name",
            new_name="productname",
        ),
    ]
