# Generated by Django 5.1.4 on 2025-01-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_rename_name_products_productname"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="gender",
            field=models.CharField(
                choices=[
                    ("men", "Men"),
                    ("women", "Women"),
                    ("unisex", "Unisex"),
                    ("kids", "Kids"),
                ],
                default="unisex",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
